---
title: "Venn Diagrams"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(eulerr)
```
"

## R Markdown

```{r }
#read all 8 tables

genelists_directory <- "input"
significant_worker_clo <- read.table(file = file.path(genelists_directory,
                                                      "differential_expression/worker/CLO_vs_CON.ids"), 
                                     head      = FALSE, 
                                     col.names = "ids")$ids
significant_worker_imi <- read.table(file = file.path(genelists_directory, 
                                                      "differential_expression/worker/IMI_vs_CON.ids"), 
                                     head      = FALSE, 
                                     col.names = "ids")$ids
significant_queen_clo  <- read.table(file = file.path(genelists_directory, 
                                                      "differential_expression/queen/CLO_vs_CON.ids"), 
                                     head      = FALSE, 
                                     col.names = "ids")$ids
significant_queen_imi  <- read.table(file = file.path(genelists_directory,
                                                      "differential_expression/queen/IMI_vs_CON.ids"), 
                                     head      = FALSE, 
                                     col.names = "ids")$ids

worker_splicing_clo    <- read.table(file = file.path(genelists_directory, 
                                                      "differential_splicing/worker/CLO_vs_CON.ids"), 
                                     head      = FALSE, 
                                     col.names = "ids")$ids



venneu <- euler(combinations = list("Worker\nclothianidin" = significant_worker_clo, 
                                    "Queen\nclothianidin" = significant_queen_clo, 
                                    "Worker imidacloprid" = significant_worker_imi,
                                    "Queen\nimidacloprid" = significant_queen_imi, 
                                    "Worker clothianidin\nsplicing" = worker_splicing_clo ))

plot(venneu,
  quantities = TRUE,
  edges=TRUE,
  labels = list(fontsize = 14))
  

```
