---
title: "comparison_pvalue_distribution"
author: "JoeColgan"
date: "18 July 2018"
output: html_document
---

Introduction:
The purpose of this script is to read in raw and adjusted p-values generated by the R package, DESeq2 (https://bioconductor.org/packages/release/bioc/html/DESeq2.html). The output of the script are plots generated by ggplot2, which allow for visualisation of the distributions of raw and adjusted p-values. 

```{r}
## Load libraries:
libraries <- c("ggplot2","ggpubr")

for (lib in libraries) {
        if (require(package = lib, character.only = TRUE)) {
                print("Successful")
        } else {
                print("Installing")
                source("https://bioconductor.org/biocLite.R")
                biocLite(pkgs = lib)
                library(lib, character.only = TRUE )
        }
}
```

Read in files for:
- Raw pvalues generated by DESeq2
- Adjusted pvalue generated by DESeq2

```{r}
##
raw_value <- read.table(file="./de_genes_for_topGO.raw.txt", header=TRUE)

## Read in adjusted p-values:
adjusted_value <- read.table(file="./de_genes_for_topGO.txt", header=TRUE)

```

Plot distribution:

```{r}
## Generate plot:
density_plot <- ggplot(data=raw_value, aes(x=pvalue)) +
                        geom_density(aes(fill="Raw", alpha=0.5)) +
                        geom_density(data= adjusted_value, aes(x=adjusted_pvalue, fill="Adjusted", alpha = 0.5)) +
                        scale_fill_manual(values = c("grey", "white")) +
                        theme_minimal()

## Generate histogram:
hist_plot <- ggplot(data=raw_value, aes(x=pvalue)) +
                        geom_histogram(aes(fill="Raw", colour="black", alpha=0.5)) +
                        geom_histogram(data= adjusted_value, aes(x=adjusted_pvalue, fill="Adjusted",  colour="black", alpha = 0.5)) +
                        scale_fill_manual(values = c("grey", "white")) +
                        scale_color_manual(values = c("black", "black")) +
                        theme_minimal()

## PLot together:
ggarrange(density_plot, hist_plot, 
          ncol = 1,
          nrow = 2,
          align="v")

```
